config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  
  resources :books, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  resources :categories, only: [:index, :new, :create, :update, :edit, :destroy]
  resources :users, only:[:index, :update, :edit, :destroy]
  resources :user_panel, only: [:index]
  resources :admin_panel, only: [:index]
  resources :welcome, only: [:index, :show, :search]

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

layout 'admin'

  def index
      if params[:search]
        @books = Book.where("title like ? OR text like ? OR description like ?",
        "%"+params[:search]+"%", "%"+params[:search]+"%", "%"+params[:search]+"%")
      else
        @books = Book.order('title ASC')
      end
  end

  def show
    @book = Book.find(params[:id])
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="main_page">
  <div class="jumbotron">
    <h1 class="display-6">Welcome to BOOKSTORE!</h1>
    <div class="action">
      <% if !user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path,
        :class => 'btn btn-primary'  %> |
        <%= link_to "Log in", new_user_session_path,
        :class => 'btn btn-success'  %>
      <% end %>
    </div>
  </div>
  <div class="jumbotron">
    <%= form_tag welcome_index_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search",:name => nil %>
    <% end %>
    <table class="table">
      <tr>
        <th class="th_center">Rating</th>
        <% if current_user %>
        <th class="th_center">Your rating</th>
        <%end%>
        <th class="th_center">Image</th>
        <th class="th_center">Category</th>
        <th class="th_center">Title</th>
        <th class="th_center">Author</th>
        <th class="th_center">Description</th>
      </tr>
      <% @books.each do |u| %> 
      <tr>
        <td class="td-width-small">
              <div class="rate_score"><%= rating_for u, "original_score",
              disable_after_rate: true, imdb_avg: true, readonly: true%></div>
              <%= rating_for u, "original_score", readonly: true%>
              Voters: <%= u.rates("original_score").count %>
        </td>
          <% if current_user %>
          <td class="td-width-small">
            Your rate <%= rating_for_user u, current_user, "original_score"%>
          </td>
          <% end %>
        <td class="td-width-small"><% if !u.picture? %>
            <%= image_tag 'book.png',
            :class => "featurette-image img-responsive"%>
            <% else %>
          <%= image_tag(u.picture.url,
          :class => "featurette-image img-responsive")%>
          <% end %><p><%= link_to("download", u.bookfile.url,
          :class => 'btn btn-xs btn-warning')  if u.bookfile? %></p></td>
        <td class="td-width-small"><%= u.category.name %></td>
        <td class="td-width-small"><%= u.title %></td>
        <td class="td-width-small"><%= u.user.nick %></td>
        <td class="td-width-small">
          <%= u.description.truncate(250,separator: /\s/) %></td>
        <td><%= link_to("Show", book_path(u),
        :class => 'btn btn-warning')%></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>