config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  
  resources :books, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  resources :categories, only: [:index, :new, :create, :update, :edit, :destroy]
  resources :users, only:[:index, :update, :edit, :destroy]
  resources :user_panel, only: [:index]
  resources :admin_panel, only: [:index]
  resources :welcome, only: [:index, :show, :search]

  root 'welcome#index'

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  has_attached_file :picture,
         :styles => {:medium => "300x300>", :thumb => "50x50>" }

  mount_uploader :bookfile, BookfileUploader
  
  validates :title,
    :presence => {:in => true, :message => " can't be empty!"},
    :length => {:within => 4..250,
    :message => " length should be between 4 and 25 characters!"}

  validates :description,
    :presence => {:in => true, :message => " can't be empty!"},
    :length => {:maximum => 950, :message => " field has too many characters!"}

  validates :text,
    :presence => {:in => true, :message => " can't be empty!"}

  validates_attachment_content_type :picture,
    content_type: ["image/jpeg", "image/gif", "image/png"] , 
    :message => '--- akceptuje tylko pliki PNG GIF i JPG ----'
  validates_attachment_size :picture, less_than: 1.megabytes, 
    :message => '--- za duży plik max rozmiar to 1 MB ----'

ratyrate_rateable 'original_score'

def self.search(search)
  if search
    where("title like ?", "%"+search+"%")
  else
    order('title ASC')
  end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

layout 'admin'

  before_action :authenticate_user!, except: [:show]

  def index
    @books = Book.search(params[:search])
    #@books = Book.order('title ASC')
    @user_books = current_user.books.search(params[:search])
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new()
    @category = Category.order('name ASC')
  end

  def create
    @book = current_user.books.new(book_params) # include current_user
    if @book.save
      flash[:notice] = "Book created."
      redirect_to new_book_path, :user_id => current_user.id
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      @book = Book.new()
      @category = Category.order('name ASC')
      render('new')
    end
  
  end

  def edit
   @book = Book.find(params[:id])
   @category = Category.order('name ASC')
   
  end
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book updated."
      redirect_to books_path
    else
      flash[:alert] = @book.errors.full_messages.to_sentence
      @book = Book.find(params[:id])
      @category = Category.order('name ASC')      
      render('edit')
    end
  end

  def destroy
    book = Book.find(params[:id]).destroy
    flash[:notice] = "Book deleted."
    redirect_to(:action => 'index')
  end

private
  def book_params
    params.require(:book).permit(:title, :description, :pages, :user_id, :category_id, :text, :picture, :bookfile)
  end

  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<table class="table table-striped">
  <% if !@book.picture.blank? %>
  <tr>
    <th>Image</th>
    <td><%= image_tag(@book.picture,
    :class => "featurette-image img-responsive") %></td>
  </tr>
  <% end %>
  <tr>
    <th><%= f.label(:picture, "Image upload") %></th>
    <td><%= f.file_field(:picture) %></td>
  </tr>
  <tr>
    <th><%= f.label(:title) %></th>
    <td><%= f.text_field(:title, :class => 'form-control') %></td>
  </tr>
  <tr>
    <th><%= f.label(:description) %></th>
    <td><%= f.text_field(:description, :class => 'form-control') %></td>
  </tr>
  <tr>
    <th><%= f.label(:text) %></th>
    <td><%= f.text_field(:text, :class => 'form-control') %></td>
  </tr>
  <tr>
    <th><%= f.label(:pages,) %></th>
    <td><%= f.text_field(:pages) %></td>
  </tr>
  <tr>
    <th><%= f.label(:category_id, "Category") %></th>
    <td><%= f.select(:category_id, @category.map{|t| [t.name, t.id ]} ,
    :class => 'form-control') %></td>
  </tr>
  <% if !@book.bookfile.blank? %>
  <tr>
    <th>File</th>
    <td><%= link_to(@book.bookfile_identifier, @book.bookfile.url) %></td>
  </tr>
  <% end %>
  <tr>
    <th><%= f.label(:bookfile, "File") %></th>
    <td><%= f.file_field(:bookfile) %></td>
  </tr>
</table>

app/views/books/_form1.html.erb
<tr>
  <td>
    <% if !u.picture? %>
      <%= image_tag 'book.png', :class => "featurette-image img-responsive"%>
    <% else %>
      <%= image_tag(u.picture.url,
      :class => "featurette-image img-responsive")%>
    <% end %>
    <p><%= link_to("download", u.bookfile.url,
    :class => 'btn btn-xs btn-warning')  if u.bookfile? %></p></td>
  <td><%= u.id %></td>
  <td><%= u.category.name %></td>
  <td><%= u.title %></td>
  <td><%= u.user.nick %></td>
  <td><%= u.description.truncate(250,separator: /\s/) %></td>
  <td><%= u.pages %></td>
  <td><%= u.text %></td>
  <td><%= link_to("Show", book_path(u), :class => 'btn btn-warning')%>
      <%= link_to("Edit", edit_book_path(u),
      :class => 'btn btn-xs btn-primary') %>
  <%= link_to("Delete", book_path(u), method: :delete,
  :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-xs btn-danger') %>
  </td>
</tr>

app/views/books/edit.html.erb
<div class="hero-unit">
  <h1>Edit book:</h1>

  <%= form_for(@book) do |f| %>

  <%= render "form",f: f %>

  <div class="buttons_down">
    <%= link_to("Back", books_path, :class => 'btn btn-warning')%>
    <%= submit_tag("Update", :class => 'btn  btn-primary') %>
  </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="container">
  <h1 class="h-position-center">List of yours books:</h1>

  <% if current_user.user_role == "admin" %>
    <p class="counter"><%= @books.size %> BOOKS</p>
  <%else%>
    <p class="counter"><%= @user_books.size %> BOOKS</p>
  <%end%>
  <p><%= link_to("New", new_book_path, :class => 'btn btn-xs btn-success') %>
  </p>
  <%= form_tag books_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search",:name => nil %>
  <% end %>

  <table class="table">
    <tr>
      <th class="th_center">Image</th>
      <th class="th_center">ID</th>
      <th class="th_center">Category</th>
      <th class="th_center">Title</th>
      <th class="th_center">Author</th>
      <th class="th_center">Description</th>
      <th class="th_center">Pages</th>
      <th class="th_center">Text</th>
    </tr>
    <% if current_user.user_role == "admin" %>
      <% @books.each do |u| %>
      <%= render "form1",u: u %>
      <%end%>
    <%else%>
      <% @user_books.each do |u| %>
      <%= render "form1",u: u %>
      <%end%>
    <%end%>
  </table>
</div>

app/views/books/new.html.erb
<div class="hero-unit">
  <h1>New Book</h1>

  <%= form_for(@book) do |f| %>

  <%= render "form",f: f %>

  <div class="buttons_down">
    <%= link_to("Back", books_path, :class => 'btn btn-warning')%>
    <%= submit_tag("Create", :class => 'btn  btn-primary') %>
  </div>

  <% end %>
</div>

app/views/books/show.html.erb
<div class="hero-unit">
<h1 class="h-position-center"><%=@book.title%></h1>
<table class="table">
  <tr><td class="td-title">Image</td><td class="td-position-center">
    <%=image_tag(@book.picture,
  :class => "img-big")%></td></tr>
  <tr><td class="td-title">ID</td><td class="td-position-center">
    <%=@book.id%></td></tr>
  <tr><td class="td-title">Category</td><td class="td-position-center">
    <%=@book.category.name%></td></tr>
  <tr><td class="td-title">Title</td><td class="td-position-center">
    <%=@book.title%></td></tr>
  <tr><td class="td-title">Author</td><td class="td-position-center">
    <%=@book.user.nick%></td></tr>
  <tr><td class="td-title">Description</td><td class="td-position-center">
    <%=@book.description%></td></tr>
  <tr><td class="td-title">Pages</td><td class="td-position-center">
    <%=@book.pages%></td></tr>
  <tr><td class="td-title">Text</td><td class="td-position-center">
    <%=@book.text%></td></tr>
  <tr><td class="td-title">File</td><td class="td-position-center">
    <%= link_to(@book.bookfile_identifier,
  @book.bookfile.url) %></td></tr>
</table>
<div class="buttons_down position-center">
  <%= link_to("Back", root_path, :class => 'btn btn-warning')%>
</div>
</br>
</div>