config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  
  resources :books, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  resources :categories, only: [:index, :new, :create, :update, :edit, :destroy]
  resources :users, only:[:index, :update, :edit, :destroy]
  resources :user_panel, only: [:index]
  resources :admin_panel, only: [:index]
  resources :welcome, only: [:index, :show, :search]

  root 'welcome#index'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

layout 'admin'

  before_action :authenticate_user!, :is_admin?

  def index
    @category = Category.order('name ASC')
  end

  def new
    @category = Category.new()
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created."
      redirect_to categories_path
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Category updated."
      redirect_to categories_path
    else  
      flash[:notice] = "Faild to edit category."
      redirect_to categories_path
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = "Category deleted."
      redirect_to categories_path
    else
      flash[:notice] = "Faild to delete category."
      redirect_to categories_path
    end
  end

 private
  def category_params
    params.require(:category).permit(:name)
  end

  def is_admin?
    unless current_user.user_role == "admin"
      flash[:alert] = "You don't have admin permition."
      redirect_to root_path 
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<table class="table table-striped">
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name, :class => 'form-control') %></td>
  </tr>
</table>

app/views/categories/edit.html.erb
<div class="hero-unit">
  <h1>Edit category:</h1>
  <%= form_for(@category) do |f| %>
  <%= render(:partial => "form", :locals => {:f => f}) %>
  <div class="buttons_down">
    <%= link_to("Back", categories_path, :class => 'btn btn-warning')%>
    <%= submit_tag("Update", :class => 'btn  btn-primary') %>
  </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p class="counter"><%= @category.size %> CATEGORIES</p>
<p><%= link_to("New", new_category_path, :class => 'btn btn-xs btn-success') %>
</p>
<table class="table">
  <tr>
  <th>ID</th>
  <th>Name</th>
  <th>Action</th>
  </tr>
  <% @category.each do |u| %>
  <tr>  
    <td><%= u.id %></td>
    <td><%= u.name %></td>
    <td><%= link_to("Edit", edit_category_path(u),
    :class => 'btn btn-xs btn-primary') %>
    <%= link_to("Delete", category_path(u), method: :delete,
    :data => {:confirm => 'Are you sure?'},
    :class => 'btn btn-xs btn-danger') %>
    </td>
  </tr>
  <%end%>
</table>

app/views/categories/new.html.erb
<div class="hero-unit">
  <h1>New Category</h1>
  <%= form_for(@category) do |f| %>
  <%= render "form",f: f %>
  <div class="buttons_down">
    <%= link_to("Back", categories_path, :class => 'btn btn-warning')%>
    <%= submit_tag("Create", :class => 'btn  btn-primary') %>
  </div>
  <% end %>
</div>