config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  
  resources :books, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  resources :categories, only: [:index, :new, :create, :update, :edit, :destroy]
  resources :users, only:[:index, :update, :edit, :destroy]
  resources :user_panel, only: [:index]
  resources :admin_panel, only: [:index]
  resources :welcome, only: [:index, :show, :search]

  root 'welcome#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>BOOKSTORE</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
 <!-- menu -->
 <% if user_signed_in? %>
  <div class="menu">
    <% if current_user.user_role == "admin" %>
      <a><%= link_to("Index", root_path, :class => 'btn btn-info')%></a>
      <a><%= link_to("Users", users_path, :class => 'btn btn-info')%>    
      <%= link_to("Categories", categories_path, :class => 'btn btn-info')%>
      <%= link_to("Books", books_path, :class => 'btn btn-info')%>        
      </a> | <a class="user_nick">Hello <%= current_user.nick.upcase %>!</a> | 
    <% else %>
      <a><%= link_to("Index", root_path, :class => 'btn btn-info')%></a>
      <a><%= link_to("My Books", books_path, :class => 'btn btn-info')%></a> | 
      <a class="user_nick">Hello <%= current_user.nick.upcase %>!</a> | 
    <% end %>
    <a><%= link_to 'Edit profile', edit_user_registration_path,
    :class => 'btn btn-info'%>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete,
      :class => 'btn btn-danger'  %> </a>
  </div>
  <% end %>     
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>BOOKSTORE</title>
    <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>BOOKSTORE</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
 <!-- menu -->
  <div class="menu">
    <a><%= link_to("My Books", books_path, :class => 'btn btn-info')%>        
    </a> | <a class="user_nick">Hello <%= current_user.nick.upcase %>!</a> | 
    <a><%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-info'%>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'btn btn-danger'  %> </a>
  </div>  
  <div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </div>
</body>
</html>